version: "3.3"

networks:
  frontend:
    ipam:
      config:
        - subnet: @META_IP_PREFIX@.255/24
services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181"
    restart: on-failure
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      frontend:
