- name: Check License Header
  uses: apache/skywalking-eyes@v0.2.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # needed only when you want License-Eye to comment on the pull request.
  # with:
      # Optional: set the log level. The default value is `info`.
      # log: debug
      # Optional: set the config file. The default value is `.licenserc.yaml`.
      # config: .licenserc.yaml
